name: Test Changelog Workflow

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  workflow_dispatch:
  push:
    branches: [ master ]
    tags:
      - 'v1'
    paths:
      - 'action.yml'
      - '.github/workflows/test-changelog-workflow.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'action.yml'
      - '.github/workflows/test-changelog-workflow.yml'

jobs:
  test-default-parameters:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Test Default Parameters
        uses: Reloaded-Project/devops-changelog@v1

  test-custom-parameters:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Test Custom Parameters
        uses: Reloaded-Project/devops-changelog@v1
        with:
          output: custom-changelog.md
          unreleased: true
          commit-limit: 10
          sort-commits: date-desc
          hide-credit: true

  test-upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Test Upload Artifact
        uses: Reloaded-Project/devops-changelog@v1
        with:
          upload-artifact: true